runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: webprofile/index.html
  upload: webprofile/index.html

- url: /(.*)
  static_files: webprofile/\1
  upload: webprofile/(.*)